///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Workshop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WorkshopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("5829c4b0-b8a5-4e1a-b8e4-4b5a6a322055")]
    public partial class WorkshopRepository : RepoGenBaseFolder
    {
        static WorkshopRepository instance = new WorkshopRepository();

        /// <summary>
        /// Gets the singleton class instance representing the WorkshopRepository element repository.
        /// </summary>
        [RepositoryFolder("5829c4b0-b8a5-4e1a-b8e4-4b5a6a322055")]
        public static WorkshopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WorkshopRepository() 
            : base("WorkshopRepository", "/", null, 0, false, "5829c4b0-b8a5-4e1a-b8e4-4b5a6a322055", ".\\RepositoryImages\\WorkshopRepository5829c4b0.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5829c4b0-b8a5-4e1a-b8e4-4b5a6a322055")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class WorkshopRepositoryFolders
    {
    }
#pragma warning restore 0436
}